[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
address = "0x1f47786624f9f6400f182246410d27a6e83d3e3ae3e6b7b40866d61717aa2b9"
transaction_hash = "0x26ddad155f9ed4605fb1c294dc910be8855e4e26d6507971dcf8a75a38744f4"
block_number = 3
seed = "chess"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x23907fff4d969aa0f22a0e53842148e65aeebe30448b050b4b71698cf179c97"
class_hash = "0x44dd10ded4a8d159b3258335cc673bf2b12bce459e9dd4382b0f03c97055298"
abi = "abis/deployments/KATANA/contracts/actions.json"
reads = []
writes = []
computed = []
name = "chess::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x72048fe4996dbabe598253296467e202fe1e398c3dcc3833f384a5a52eabab"
name = "chess::models::game::game"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "winner"
type = "Color"
key = false

[[models.members]]
name = "white"
type = "ContractAddress"
key = false

[[models.members]]
name = "black"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x57c396a5c3222b750ff5241462040d0c1c9e9d1789e7b2e6bd3fff7d68dfd85"
name = "chess::models::game::game_turn"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player_color"
type = "Color"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1490d0d735f07fbcb30479fb9fb1674ebe2e0489ca8bb788121124be078de4f"
name = "chess::models::piece::piece"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "position"
type = "Vec2"
key = true

[[models.members]]
name = "color"
type = "Color"
key = false

[[models.members]]
name = "piece_type"
type = "PieceType"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1d6bd75d205c34901674c6e42c282b3bfb8d179a4a60de2b2a4d6329ad1766e"
name = "chess::models::player::player"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "color"
type = "Color"
key = false
