kind = "DojoModel"
class_hash = "0x72048fe4996dbabe598253296467e202fe1e398c3dcc3833f384a5a52eabab"
name = "chess::models::game::game"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "winner"
type = "Color"
key = false

[[members]]
name = "white"
type = "ContractAddress"
key = false

[[members]]
name = "black"
type = "ContractAddress"
key = false
