kind = "DojoModel"
class_hash = "0x57c396a5c3222b750ff5241462040d0c1c9e9d1789e7b2e6bd3fff7d68dfd85"
name = "chess::models::game::game_turn"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_color"
type = "Color"
key = false
