kind = "DojoContract"
class_hash = "0x44dd10ded4a8d159b3258335cc673bf2b12bce459e9dd4382b0f03c97055298"
abi = "abis/base/contracts/actions.json"
reads = []
writes = []
computed = []
name = "chess::actions::actions"
